# Generated by Django 5.2.3 on 2025-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('fail', 'Неудачно')], default='success', max_length=10),
        ),
    ]
