# Generated by Django 5.2.3 on 2025-10-14 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_is_active_alter_recipient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='authentication.recipient', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Тело письма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема письма'),
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=10, verbose_name='Статус')),
                ('server_response', models.TextField(blank=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mailing', verbose_name='Рассылка')),
            ],
        ),
    ]
