# Generated by Django 5.2.3 on 2025-10-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_customuser_avatar_mailing_user_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки'),
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=20)),
                ('server_response', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='authentication.mailing')),
            ],
        ),
    ]
